### PR TITLE
Create main.yml

### PR DESCRIPTION
**Pull request by Atilla87**

### CODE REVIEW

**Comment by persianpros** [comment]
Why do we need this?

**Comment by Atilla87** [comment]
Sorry my mistake

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Persian Prince <notifications@github.com>
Gesendet: Friday, November 29, 2019 9:10:35 AM
An: OpenVisionE2/meta-dream <meta-dream@noreply.github.com>
Cc: Atilla87 <ati87akbulut@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [OpenVisionE2/meta-dream] Create main.yml (#11)


Why do we need this?

**Comment by Atilla87** [comment]
Ist my first time i try but dont understand this is too much for me.
I only Need openvision for dreambox one or vu ultimo 4k???
Another Images i can download and start but for openvision must is anything to do
i tried openvision on another box ist realy the best one.
Can you send me a link or anything to download???

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10


Von: Persian Prince <notifications@github.com>
Gesendet: Sunday, December 1, 2019 12:06:38 AM
An: OpenVisionE2/meta-dream <meta-dream@noreply.github.com>
Cc: Atilla87 <ati87akbulut@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [OpenVisionE2/meta-dream] Create main.yml (#11)


Closed #11<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenVisionE2%2Fmeta-dream%2Fpull%2F11&data=02%7C01%7C%7C5967316a5f7940c0e5e408d775e9f4b5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637107519999697875&sdata=urvzFhSDgZpTJgJwheLqgEIXnkNmXykc7zwREczWApA%3D&reserved=0>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenVisionE2%2Fmeta-dream%2Fpull%2F11%3Femail_source%3Dnotifications%26email_token%3DAMASRGXN43SXCOIEZ3CSG2TQWLWX5A5CNFSM4JS2HNPKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOVF2RGYY%23event-2843022179&data=02%7C01%7C%7C5967316a5f7940c0e5e408d775e9f4b5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637107519999707886&sdata=oUsferwBO70RxXBTLT7qhHtL49SuFZr%2FzIIbwwK2Cjg%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMASRGXWHJMY26ZUU4PJLX3QWLWX5ANCNFSM4JS2HNPA&data=02%7C01%7C%7C5967316a5f7940c0e5e408d775e9f4b5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637107519999717903&sdata=M3UGov6UfFB6eQmEsR1%2BhnxUsJ1n1ORhiyuK3h0uxMk%3D&reserved=0>.
Von: Persian Prince<mailto:notifications@github.com>
Gesendet: Sonntag, 1. Dezember 2019 00:06
Betreff: Re: [OpenVisionE2/meta-dream] Create main.yml (#11)


Closed #11<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenVisionE2%2Fmeta-dream%2Fpull%2F11&data=02%7C01%7C%7C5967316a5f7940c0e5e408d775e9f4b5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637107519999697875&sdata=urvzFhSDgZpTJgJwheLqgEIXnkNmXykc7zwREczWApA%3D&reserved=0>.

**Comment by persianpros** [comment]
Did you try my test builds: http://www.mediafire.com/folder/nlkzsek307bpf/openvision-test-images-by-persianprince ?

Here's another test build by one of our testers: https://www.mediafire.com/file/9iya60chyx0jrds/openvision-enigma2-upcoming-multilanguage-9.2-r59-vuultimo4k-20191122_usb.zip

**Comment by Atilla87** [comment]
Hey cool!

I trie your build, thank you soo much

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Persian Prince<mailto:notifications@github.com>
Gesendet: Sonntag, 1. Dezember 2019 00:15
An: OpenVisionE2/meta-dream<mailto:meta-dream@noreply.github.com>
Cc: Atilla87<mailto:ati87akbulut@hotmail.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [OpenVisionE2/meta-dream] Create main.yml (#11)


Did you try my test builds: http://www.mediafire.com/folder/nlkzsek307bpf/openvision-test-images-by-persianprince<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.mediafire.com%2Ffolder%2Fnlkzsek307bpf%2Fopenvision-test-images-by-persianprince&data=02%7C01%7C%7C9a108d3129c04684e12308d775eb35b8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637107525385641214&sdata=rXMeGkorQp7D9m2Ok%2Bgl1gSLP0Fr0aq%2B5YiUzr1lils%3D&reserved=0> ?

Here's another test build by one of our testers: https://www.mediafire.com/file/9iya60chyx0jrds/openvision-enigma2-upcoming-multilanguage-9.2-r59-vuultimo4k-20191122_usb.zip<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.mediafire.com%2Ffile%2F9iya60chyx0jrds%2Fopenvision-enigma2-upcoming-multilanguage-9.2-r59-vuultimo4k-20191122_usb.zip&data=02%7C01%7C%7C9a108d3129c04684e12308d775eb35b8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637107525385651225&sdata=SWeiQm6UY5hd7BOo7FR4LNvW6vjhpYfhF%2Bj6xbvBiEc%3D&reserved=0>

**Comment by Atilla87** [comment]
Hello,

The DreamOne image dont works do you have a working image for me please?




Best regards!
________________________________
Von: Persian Prince <notifications@github.com>
Gesendet: Sonntag, 1. Dezember 2019 00:15
An: OpenVisionE2/meta-dream <meta-dream@noreply.github.com>
Cc: Atilla87 <ati87akbulut@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [OpenVisionE2/meta-dream] Create main.yml (#11)


Did you try my test builds: http://www.mediafire.com/folder/nlkzsek307bpf/openvision-test-images-by-persianprince<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.mediafire.com%2Ffolder%2Fnlkzsek307bpf%2Fopenvision-test-images-by-persianprince&data=02%7C01%7C%7C9a108d3129c04684e12308d775eb35b8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637107525385641214&sdata=rXMeGkorQp7D9m2Ok%2Bgl1gSLP0Fr0aq%2B5YiUzr1lils%3D&reserved=0> ?

Here's another test build by one of our testers: https://www.mediafire.com/file/9iya60chyx0jrds/openvision-enigma2-upcoming-multilanguage-9.2-r59-vuultimo4k-20191122_usb.zip<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.mediafire.com%2Ffile%2F9iya60chyx0jrds%2Fopenvision-enigma2-upcoming-multilanguage-9.2-r59-vuultimo4k-20191122_usb.zip&data=02%7C01%7C%7C9a108d3129c04684e12308d775eb35b8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637107525385651225&sdata=SWeiQm6UY5hd7BOo7FR4LNvW6vjhpYfhF%2Bj6xbvBiEc%3D&reserved=0>

**Pull request closed without merging**
